name: Build and Push Docker Image

on:
  push:
    branches:
      - main # Trigger on push to the 'main' branch
    tags:
      - 'v*' # Trigger on tags starting with 'v'

env:
  REGISTRY: ghcr.io # Use GitHub Container Registry
  IMAGE_NAME: ${{ github.repository }} # Image name based on the repo name (e.g., owner/repo)

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Necessary for pushing to GHCR

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} # Use the built-in GITHUB_TOKEN for GHCR

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
            type=sha,format=short
            type=ref,event=branch
            type=semver,pattern=v{{version}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: . # Path to the build context (where the Dockerfile is)
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}